function parseDeal(deal,was,now){var d=String(deal||"").toLowerCase();was=+was||0;now=+now||0;if(!now&&was)now=was;if(/1\s*\+\s*1|1\+1/.test(d)){var unit=now&&was&&now<was?now:Math.round((was||now*2)/2);return{qty:2,cents:unit,line:unit*2,label:"1+1"};}return{qty:1,cents:now||was,line:now||was,label:deal||"actie"};}
function extraByKey(k){if(!k||String(k).indexOf("e:")!==0)return null;var i=+String(k).split(":")[1];return(S.extras||[])[i]||null;}
function findExtra(n,sid){S.extras=S.extras||[];for(var i=0;i<S.extras.length;i++){if(S.extras[i].n===n&&(S.extras[i].sid||"")===(sid||""))return i;}return -1;}
function syncLine(e){e.q=Math.max(0,+e.q||0);e.line=(e.cents||0)*e.q;}
function bumpExtra(i,d){var e=(S.extras||[])[i];if(!e)return;e.q=Math.max(0,(+e.q||1)+d);if(e.q<=0)S.extras.splice(i,1);else syncLine(e);if(typeof save==="function")save();if(typeof drawList==="function")drawList();}
function addDealFull(row){if(!row||!row.n)return;S.extras=S.extras||[];var pack=parseDeal(row.deal,row.was,row.now);var i=findExtra(row.n,row.sid);if(i>=0){bumpExtra(i,1);if(typeof toast==="function")toast((S.extras[i]?S.extras[i].q:1)+"× "+row.n);return;}S.extras.push({n:row.n,q:1,s:"Houdbaar",sid:row.sid||"",deal:row.deal||"",was:row.was||0,cents:pack.cents||row.now||0,line:pack.cents||row.now||0,label:pack.label,img:row.img||"",pack:row.qty||row.pack||""});if(typeof save==="function")save();if(typeof drawList==="function")drawList();if(typeof toast==="function")toast(row.n+" staat op de lijst");}
function applyDealPrice(){if(typeof unitPrice!=="function"||unitPrice._deal)return;var _u=unitPrice;unitPrice=function(cat,retailer,brand,k){var ex=extraByKey(k);if(ex&&ex.sid&&ex.sid!==retailer)return null;if(ex&&ex.cents)return ex.cents;return _u(cat,retailer,brand,k);};unitPrice._deal=true;}
function paintQty(){(S.extras||[]).forEach(function(e,i){var key="e:"+i+":"+e.n;var w=null;document.querySelectorAll("#lijstbody .swipewrap").forEach(function(n){if(n.getAttribute("data-k")===key)w=n;});if(!w)return;var row=w.querySelector(".listrow")||w;if(row.querySelector(".qtybox")){row.querySelector(".qtyn").textContent=String(e.q||1);return;}var box=document.createElement("div");box.className="qtybox";box.innerHTML="<button type=button class=qtybtn data-act=qty data-i="+i+" data-d=-1>−</button><span class=qtyn>"+(e.q||1)+"</span><button type=button class=qtybtn data-act=qty data-i="+i+" data-d=1>+</button>";row.appendChild(box);});}
applyDealPrice();
if(typeof drawList==="function"&&!drawList._deal){var _dl=drawList;drawList=function(){_dl();paintQty();};drawList._deal=true;}
if(!document.getElementById("qtycss")){var st=document.createElement("style");st.id="qtycss";st.textContent=".qtybox{display:flex;align-items:center;gap:6px;flex:none;margin-left:auto}.qtybtn{width:34px;height:34px;border:0;border-radius:10px;background:#EDE0D0;font:800 18px Outfit,sans-serif}.qtyn{min-width:16px;text-align:center;font-weight:800}";document.head.appendChild(st);}
