function parseDeal(deal,was,now){var d=String(deal||"").toLowerCase();was=+was||0;now=+now||0;if(!now&&was)now=was;if(/1\s*\+\s*1|1\+1|one_plus_one|\+\s*1 gratis/.test(d)){var unit=now&&was&&now<was?now:Math.round((was||now*2)/2);return{qty:2,cents:unit,line:unit*2,label:"1+1 · 2 stuks"};}var m=d.match(/(\d+)\s*voor\s*€?\s*([0-9]+[.,]?[0-9]*)/);if(m){var qty=+m[1];var raw=parseFloat(m[2].replace(",","."));var line=Math.round(raw>=20?raw:raw*100);return{qty:qty,cents:Math.round(line/qty),line:line,label:qty+" voor €"+(line/100).toFixed(2).replace(".",",")};}if(/2e halv/.test(d)){var full=was||now;var half=Math.round(full/2);return{qty:2,cents:Math.round((full+half)/2),line:full+half,label:"2e halve prijs · 2 stuks"};}return{qty:1,cents:now||was,line:now||was,label:deal||"actie"};}
function extraByKey(k){if(!k||String(k).indexOf("e:")!==0)return null;var i=+String(k).split(":")[1];return(S.extras||[])[i]||null;}
function applyDealPrice(){if(typeof unitPrice!=="function"||unitPrice._deal)return;var _u=unitPrice;unitPrice=function(cat,retailer,brand,k){var ex=extraByKey(k);if(ex&&ex.line!=null){if(ex.sid&&ex.sid!==retailer)return null;return ex.cents!=null?ex.cents:Math.round(ex.line/Math.max(+ex.q||1,1));}var sku=S.sku&&S.sku[k];if(sku&&sku.now&&(!sku.s||sku.s===retailer))return +sku.now;return _u(cat,retailer,brand,k);};unitPrice._deal=true;}
function findExtra(n,sid){S.extras=S.extras||[];for(var i=0;i<S.extras.length;i++){if(S.extras[i].n===n&&(S.extras[i].sid||"")===(sid||""))return i;}return -1;}
function syncLine(e){var unit=e.cents||0;e.q=Math.max(0,+e.q||0);e.line=unit*e.q;}
function bumpExtra(i,d){var e=(S.extras||[])[i];if(!e)return;e.q=Math.max(0,(+e.q||1)+d);if(e.q<=0){S.extras.splice(i,1);}else syncLine(e);if(typeof save==="function")save();if(typeof drawList==="function")drawList();if(typeof drawStores==="function")drawStores();if(typeof drawFolder==="function")drawFolder();}
function addDealFull(row){if(!row||!row.n)return;S.extras=S.extras||[];var pack=parseDeal(row.deal,row.was,row.now);if(!pack.line&&row.now)pack={qty:1,cents:+row.now,line:+row.now,label:row.deal||"actie"};var i=findExtra(row.n,row.sid);if(i>=0){bumpExtra(i,pack.qty||1);if(typeof toast==="function")toast((S.extras[i]?S.extras[i].q:0)+"× "+row.n);return;}S.extras.push({n:row.n,q:pack.qty||1,s:row.aisle||"Houdbaar",sid:row.sid||"",deal:row.deal||"",was:row.was||0,cents:pack.cents,line:pack.line,label:pack.label,img:row.img||"",pack:row.qty||row.pack||""});if(typeof save==="function")save();if(typeof drawList==="function")drawList();if(typeof drawStores==="function")drawStores();if(typeof drawFolder==="function")drawFolder();if(typeof toast==="function")toast((pack.qty||1)+"× "+row.n+" op de lijst");}
function restampStores(){var host=document.getElementById("stores");if(!host||typeof buildList!=="function")return;var items=buildList().filter(function(i){return!S.checked[i.k];});var scores=activeStores().map(function(r){var actie=0,rest=0,have=0,miss=[],nAct=0;items.forEach(function(i){var ex=extraByKey(i.k);if(ex&&ex.sid){if(ex.sid===r.id){actie+=ex.line||0;have++;nAct++;}else miss.push(i.n);return;}var pr=unitPrice(i.cat,r.id,S.brand,i.k);if(pr==null)miss.push(i.n);else{rest+=Math.round(pr*Math.max(+i.q||1,0.5));have++;}});return Object.assign({},r,{actie:actie,rest:rest,total:actie+rest,have:have,miss:miss,nAct:nAct,cov:items.length?Math.round(100*have/items.length):100});});var best=null;var withDeal=scores.filter(function(s){return s.nAct>0;});if(withDeal.length){var maxA=Math.max.apply(null,withDeal.map(function(s){return s.nAct;}));best=withDeal.filter(function(s){return s.nAct===maxA;}).sort(function(a,b){return a.actie-b.actie;})[0];}else{var usable=scores.filter(function(s){return s.have>0;});if(usable.length){var maxC=Math.max.apply(null,usable.map(function(s){return s.cov;}));best=usable.filter(function(s){return s.cov===maxC;}).sort(function(a,b){return a.total-b.total;})[0];}}host.innerHTML=scores.map(function(s){var isBest=best&&s.id===best.id;var bits=[];if(s.nAct)bits.push(s.nAct+" actie €"+(s.actie/100).toFixed(2).replace(".",","));if(s.rest)bits.push("rest indicatie €"+(s.rest/100).toFixed(2).replace(".",","));if(!s.have)bits.push("geen van deze acties");else if(s.miss.length)bits.push("mist "+s.miss.slice(0,2).join(", "));var som=s.have?("€"+(s.total/100).toFixed(2).replace(".",",")):"—";return "<div class=store><div><b>"+s.n+"</b> "+(isBest?"<span class='badge best'>hier kopen</span>":"")+"<div class=meta>"+bits.join(" · ")+"</div></div><div class=price>"+som+"</div></div>";}).join("");}
function paintQty(){(S.extras||[]).forEach(function(e,i){var key="e:"+i+":"+e.n;var w=Array.prototype.filter.call(document.querySelectorAll("#lijstbody .swipewrap, #lijstbody .listrow"),function(n){return n.getAttribute("data-k")===key;})[0];if(!w)return;var row=w.querySelector(".listrow")||w;if(row.querySelector(".qtybox")){row.querySelector(".qtyn").textContent=e.q||1;var price=row.querySelector(".price");if(price)price.textContent="€"+((e.line||0)/100).toFixed(2).replace(".",",");return;}var box=document.createElement("div");box.className="qtybox";box.innerHTML="<button type=button class=qtybtn data-act=qty data-i="+i+" data-d=-1>−</button><span class=qtyn>"+(e.q||1)+"</span><button type=button class=qtybtn data-act=qty data-i="+i+" data-d=1>+</button>";var price=row.querySelector(".price");if(price){price.textContent="€"+((e.line||0)/100).toFixed(2).replace(".",",");row.insertBefore(box,price);}else row.appendChild(box);});if(typeof drawFolder==="function"){var rows=window._folderRows||[];rows.forEach(function(r,idx){var i=findExtra(r.n,r.s);var btn=document.querySelector("#folderbody [data-act=adddeal][data-idx='"+idx+"']");if(!btn)return;var badge=btn.querySelector(".qbadge");if(i<0){if(badge)badge.remove();return;}if(!badge){badge=document.createElement("span");badge.className="qbadge";btn.appendChild(badge);}badge.textContent=S.extras[i].q;});}}
applyDealPrice();
if(typeof drawList==="function"&&!drawList._deal){var _dl=drawList;drawList=function(){_dl();paintQty();};drawList._deal=true;}
if(typeof drawStores==="function"&&!drawStores._score){var _ds=drawStores;drawStores=function(){_ds();restampStores();};drawStores._score=true;}
if(typeof drawFolder==="function"&&!drawFolder._qty){var _df=drawFolder;drawFolder=function(){_df();paintQty();};drawFolder._qty=true;}
document.addEventListener("click",function(e){var t=e.target.closest&&e.target.closest("[data-act=qty]");if(!t)return;e.preventDefault();e.stopPropagation();bumpExtra(+t.getAttribute("data-i"),+t.getAttribute("data-d"));},true);
if(!document.getElementById("qtycss")){var st=document.createElement("style");st.id="qtycss";st.textContent=".qtybox{display:flex;align-items:center;gap:6px;flex:none}.qtybtn{width:32px;height:32px;border:0;border-radius:10px;background:#EDE0D0;font:800 18px Outfit,sans-serif;color:#2A1810}.qtyn{min-width:18px;text-align:center;font-weight:800}.qbadge{min-width:22px;height:22px;border-radius:11px;background:#C45A38;color:#fff;font:800 12px Outfit,sans-serif;display:grid;place-items:center;margin-left:6px}.thumb{width:44px;height:44px;border-radius:12px;object-fit:cover;background:#EDE0D0;flex:none}";document.head.appendChild(st);}
