S.folderStore=S.folderStore||"alle";
S.folderQ=S.folderQ||"";
function storeName(id){var s=(typeof STORES!=="undefined"?STORES:[]).filter(function(x){return x.id===id;})[0];return s?s.n:id;}
function fullItems(){return (window.FOLDER_FULL&&window.FOLDER_FULL.items)||[];}
function packOf(r){return (r&&(r.q||r.qty||r.pack))||"";}
function dealText(r){var raw=String(r.deal||"").trim();if(!raw||/^(feed|folder|actie|bonus|promotie)$/i.test(raw))return (r.was&&r.now&&r.was>r.now)?(Math.round(100*(r.was-r.now)/r.was)+"% korting"):"";return raw;}
function euroc(c){c=+c||0;return "\u20ac"+(c/100).toFixed(2).replace(".",",");}
function drawFolder(){var host=document.getElementById("folderbody");if(!host)return;var line=document.getElementById("folderline");if(line)line.textContent=fullItems().length+" acties";var sc=host.parentNode;if(sc&&!document.getElementById("folderq")){var inp=document.createElement("input");inp.id="folderq";inp.placeholder="Zoek in de folder";inp.value=S.folderQ||"";inp.addEventListener("input",function(){S.folderQ=inp.value;drawFolder();});sc.insertBefore(inp,host);}var pick=document.getElementById("folderpick");if(pick){var stores=(typeof STORES!=="undefined"&&STORES.length)?STORES:[{id:"dirk",n:"Dirk"},{id:"ah",n:"Albert Heijn"},{id:"lidl",n:"Lidl"},{id:"jumbo",n:"Jumbo"},{id:"plus",n:"Plus"}];pick.innerHTML=["alle"].concat(stores.map(function(s){return s.id;})).map(function(id){var n=id==="alle"?"Alle":storeName(id);return "<button type=button class='chip "+(S.folderStore===id?"on":"")+"' data-act=fstore data-id="+id+">"+n+"</button>";}).join("");}var q=(S.folderQ||"").toLowerCase().trim();var rows=fullItems().filter(function(r){if(S.folderStore&&S.folderStore!=="alle"&&r.s!==S.folderStore)return false;if(!q)return true;return (r.n+" "+(r.b||"")+" "+packOf(r)).toLowerCase().indexOf(q)>=0;});if(!rows.length){host.innerHTML="<p class=note>Nog geen folderregels.</p>";window._folderRows=[];return;}var html="";rows.slice(0,80).forEach(function(r,idx){html+="<button type=button class=listrow data-act=adddeal data-idx="+idx+">"+(r.img?"<img class=thumb alt='' referrerpolicy='no-referrer' onerror=\"this.style.visibility='hidden'\" src=\""+String(r.img).replace(/\"/g,"")+"\">":"")+"<div style=flex:1><b>"+String(r.n||"").replace(/'/g,"")+"</b><div class=meta>"+[storeName(r.s),packOf(r),dealText(r)].filter(Boolean).join(" \u00b7 ")+"</div></div><div class=price>"+(r.now?euroc(r.now):"")+"</div></button>";});host.innerHTML=html;window._folderRows=rows.slice(0,80);}
document.addEventListener("click",function(e){var fs=e.target.closest&&e.target.closest("[data-act=fstore]");if(fs){S.folderStore=fs.getAttribute("data-id");drawFolder();}});
if(typeof show==="function"&&!show._folderWrap){var _show=show;show=function(id){_show(id);if(id==="folder")drawFolder();if(id==="lijst"&&typeof paintFolderList==="function")paintFolderList();};show._folderWrap=true;}
fetch("bonus.json",{cache:"no-store"}).then(function(r){return r.json();}).then(function(d){if(d&&typeof BONUS!=="undefined")["ah","jumbo","lidl","plus","dirk"].forEach(function(r){BONUS[r]=d[r]||{};});}).catch(function(){});
Promise.all(["ah","jumbo","lidl","plus","dirk"].map(function(s){return fetch("folder-"+s+".json",{cache:"no-store"}).then(function(r){return r.json();});})).then(function(arr){var items=[];arr.forEach(function(d){(d.items||[]).forEach(function(it){if(it.qty&&!it.q)it.q=it.qty;items.push(it);});});window.FOLDER_FULL={items:items};var f=document.getElementById("folder");if(f&&f.classList.contains("on"))drawFolder();}).catch(function(){});
