S.folderStore=S.folderStore||"alle";
S.folderQ=S.folderQ||"";
function applyFolder(d){if(!d||typeof BONUS==="undefined")return;["ah","jumbo","lidl","plus","dirk"].forEach(function(r){BONUS[r]=d[r]||{};});window.FOLDER_META=d;}
function normItem(it){if(!it)return it;if(it.qty&&!it.q)it.q=it.qty;return it;}
function applyFull(d){if(d&&d.items)d.items.forEach(normItem);window.FOLDER_FULL=d;var f=document.getElementById("folder");if(f&&f.classList.contains("on"))drawFolder();}
function storeName(id){var s=(typeof STORES!=="undefined"?STORES:[]).filter(function(x){return x.id===id;})[0];return s?s.n:id;}
function fullItems(){return (window.FOLDER_FULL&&window.FOLDER_FULL.items)||[];}
function packOf(r){return (r&&(r.q||r.qty||r.pack))||"";}
function dealText(r){var raw=String(r.deal||"").trim();if(!raw||/^(feed|folder|actie|bonus|promotie)$/i.test(raw))return (r.was&&r.now&&r.was>r.now)?(Math.round(100*(r.was-r.now)/r.was)+"% korting"):"";return raw;}
function putOnList(hit){if(!hit||!hit.n)return;S.extras=S.extras||[];var i=-1;for(var x=0;x<S.extras.length;x++){if(S.extras[x].n===hit.n&&(S.extras[x].sid||"")===(hit.s||""))i=x;}if(i>=0){S.extras[i].q=(+S.extras[i].q||1)+1;S.extras[i].line=(S.extras[i].cents||hit.now||0)*S.extras[i].q;}else{S.extras.push({n:hit.n,q:1,s:"Houdbaar",sid:hit.s||"",deal:hit.deal||"",was:hit.was||0,cents:hit.now||0,line:hit.now||0,img:hit.img||"",pack:packOf(hit)});i=S.extras.length-1;}if(typeof save==="function")save();if(typeof drawList==="function")drawList();if(typeof drawStores==="function")drawStores();if(typeof toast==="function")toast(S.extras[i].q+"× "+hit.n+" op de lijst");}
function drawFolder(){var host=document.getElementById("folderbody");if(!host)return;var line=document.getElementById("folderline");if(line)line.textContent=fullItems().length+" acties";var sc=host.parentNode;if(sc&&!document.getElementById("folderq")){var inp=document.createElement("input");inp.id="folderq";inp.placeholder="Zoek in de folder";inp.value=S.folderQ||"";inp.addEventListener("input",function(){S.folderQ=inp.value;drawFolder();});sc.insertBefore(inp,host);}var pick=document.getElementById("folderpick");if(pick){var stores=(typeof STORES!=="undefined"&&STORES.length)?STORES:[{id:"dirk",n:"Dirk"},{id:"ah",n:"Albert Heijn"},{id:"lidl",n:"Lidl"},{id:"jumbo",n:"Jumbo"},{id:"plus",n:"Plus"}];pick.innerHTML=["alle"].concat(stores.map(function(s){return s.id;})).map(function(id){var n=id==="alle"?"Alle":storeName(id);return "<button type=button class='chip "+(S.folderStore===id?"on":"")+"' data-act=fstore data-id="+id+">"+n+"</button>";}).join("");}var q=(S.folderQ||"").toLowerCase().trim();var rows=fullItems().filter(function(r){if(S.folderStore&&S.folderStore!=="alle"&&r.s!==S.folderStore)return false;if(!q)return true;return (r.n+" "+(r.b||"")+" "+packOf(r)).toLowerCase().indexOf(q)>=0;});if(!rows.length){host.innerHTML="<p class=note>Nog geen folderregels. Trek naar beneden of kies een winkel.</p>";return;}var html="";rows.slice(0,80).forEach(function(r,idx){var price=r.now?("€"+(r.now/100).toFixed(2).replace(".",",")):"";var nm=String(r.n||"").replace(/'/g,"");html+="<button type=button class=listrow data-act=adddeal data-idx="+idx+">"+(r.img?"<img class=thumb alt='' referrerpolicy='no-referrer' onerror=\"this.style.visibility='hidden'\" src=\""+String(r.img).replace(/\"/g,"")+"\">":"")+"<div style=flex:1><b>"+nm+"</b><div class=meta>"+[storeName(r.s),packOf(r),dealText(r)].filter(Boolean).join(" · ")+"</div></div><div class=price>"+price+"</div></button>";});host.innerHTML=html;window._folderRows=rows.slice(0,80);}
document.addEventListener("click",function(e){var fs=e.target.closest&&e.target.closest("[data-act=fstore]");if(fs){S.folderStore=fs.getAttribute("data-id");drawFolder();return;}var ad=e.target.closest&&e.target.closest("[data-act=adddeal]");if(ad){e.preventDefault();var hit=(window._folderRows||[])[+ad.getAttribute("data-idx")];if(hit)putOnList(hit);}});
if(typeof show==="function"&&!show._folderWrap){var _show=show;show=function(id){_show(id);if(id==="folder")drawFolder();if(id==="winkel"&&typeof drawStores==="function")drawStores();};show._folderWrap=true;}
fetch("bonus.json?v=8",{cache:"no-store"}).then(function(r){return r.json();}).then(applyFolder).catch(function(){});
Promise.all(["ah","jumbo","lidl","plus","dirk"].map(function(s){return fetch("folder-"+s+".json",{cache:"no-store"}).then(function(r){return r.json();});})).then(function(arr){var items=[];arr.forEach(function(d){(d.items||[]).forEach(function(it){items.push(normItem(it));});});applyFull({items:items});}).catch(function(){});
(function(src,flag){if(window[flag])return;window[flag]=1;var s=document.createElement("script");s.src=src;document.body.appendChild(s);})("deal.js?v=20","_dealjs");
