S.sku=S.sku||{};
function ensureSkuPanel(){if(document.getElementById("skup"))return;var p=document.createElement("section");p.className="panel";p.id="skup";p.innerHTML="<div class=hd><button class='btn s w' id=skclose>Sluit</button><b>Kies product</b></div><div class=sc><p class=note id=sknote></p><div id=skbody></div></div>";document.querySelector(".phone").appendChild(p);document.getElementById("skclose").onclick=function(){p.classList.remove("on");};}
function skuMatches(item){if(!item||String(item.k||"").indexOf("e:")===0)return[];var name=String(item.n||"").toLowerCase();var toks=name.split(/[^a-z0-9]+/).filter(function(w){return w.length>=4&&["voor","met","van","stuks","pack","original","taste","extra"].indexOf(w)<0;});if(!toks.length)return[];var main=toks[0];var rows=(window.FOLDER_FULL&&window.FOLDER_FULL.items)||[];var stores=typeof activeStores==="function"?activeStores().map(function(s){return s.id;}):["ah","jumbo","lidl","plus","dirk"];return rows.filter(function(r){if(stores.indexOf(r.s)<0)return false;var hay=(r.n+" "+(r.b||"")).toLowerCase();if(hay.indexOf(main)<0)return false;var hit=0;for(var i=0;i<toks.length;i++)if(hay.indexOf(toks[i])>=0)hit++;return hit>=Math.min(2,toks.length);}).slice(0,8);}
function openSku(k){if(!k||String(k).indexOf("e:")===0)return;ensureSkuPanel();var items=typeof buildList==="function"?buildList():[];var item=items.filter(function(i){return i.k===k;})[0]||{k:k,n:k};S._skuK=k;document.getElementById("sknote").textContent="Merk voor "+item.n+". Alleen echte hits.";var hits=skuMatches(item);var html="<button class=listrow data-act=skupick data-generic=1><div style=flex:1><b>"+item.n+"</b><div class=meta>Laat zo · jij kiest in de winkel</div></div></button>";hits.forEach(function(r,i){var price=r.now?("€"+(r.now/100).toFixed(2).replace(".",",")):"";html+="<button class=listrow data-act=skupick data-i="+i+"><div style=flex:1><b>"+r.n+"</b><div class=meta>"+(typeof storeName==="function"?storeName(r.s):r.s)+(r.qty?" · "+r.qty:"")+"</div></div><div class=price>"+price+"</div></button>";});if(!hits.length)html+="<p class=note>Geen harde hit in de folder. Tik Actie voor het exacte product.</p>";document.getElementById("skbody").innerHTML=html;window._skuHits=hits;document.getElementById("skup").classList.add("on");}
function pickSku(generic,idx){var k=S._skuK;if(!k)return;if(generic)delete S.sku[k];else{var r=window._skuHits[idx];if(r)S.sku[k]={n:r.n,b:r.b||"",s:r.s,now:r.now,deal:r.deal};}if(typeof save==="function")save();var p=document.getElementById("skup");if(p)p.classList.remove("on");if(typeof drawList==="function")drawList();}
function paintSkuNames(){if(!S.sku)return;document.querySelectorAll("#lijstbody .swipewrap").forEach(function(w){var k=w.getAttribute("data-k");if(!k||k.indexOf("e:")===0)return;var pick=S.sku[k];if(!pick||!pick.n)return;var b=w.querySelector("b");if(b)b.textContent=pick.n;});}
function paintSteppers(){document.querySelectorAll("#lijstbody .swipewrap").forEach(function(w){var k=w.getAttribute("data-k")||"";if(k.indexOf("e:")!==0)return;if(w.querySelector(".qtybox"))return;var i=+k.split(":")[1];var e=(S.extras||[])[i];if(!e)return;var row=w.querySelector(".listrow");if(!row)return;var box=document.createElement("div");box.className="qtybox";box.innerHTML="<button type=button class=qtybtn data-act=qty data-i="+i+" data-d=-1>−</button><span class=qtyn>"+(e.q||1)+"</span><button type=button class=qtybtn data-act=qty data-i="+i+" data-d=1>+</button>";var old=row.querySelector(".meta:last-child");if(old&&old.parentNode===row)old.remove();row.appendChild(box);});}
function wireBordSwipe(){var root=document.getElementById("days");if(!root)return;root.querySelectorAll(".dayrow").forEach(function(row){var d=row.getAttribute("data-d");if(!S.plan[d]||!S.plan[d].id)return;if(row.parentNode.classList.contains("swipewrap"))return;var wrap=document.createElement("div");wrap.className="swipewrap right";wrap.setAttribute("data-d",d);wrap.innerHTML="<div class=swipebg>Weg van bord</div>";row.parentNode.insertBefore(wrap,row);wrap.appendChild(row);});}
function dropMeal(d){delete S.plan[d];delete S.eaten[d];if(typeof save==="function")save();if(typeof drawBord==="function")drawBord();}
if(typeof drawBord==="function"&&!drawBord._pick){var _b=drawBord;drawBord=function(){_b();wireBordSwipe();};drawBord._pick=true;}
if(typeof drawList==="function"&&!drawList._pick){var _l=drawList;drawList=function(){_l();paintSkuNames();paintSteppers();};drawList._pick=true;}
(function(){var root=document.getElementById("days");if(!root)return;var startX=0,cur=null,dx=0,locked=false;root.addEventListener("touchstart",function(ev){var wrap=ev.target.closest(".swipewrap.right");if(!wrap||ev.target.closest("button"))return;startX=ev.changedTouches[0].clientX;cur=wrap;dx=0;locked=false;},{passive:true});root.addEventListener("touchmove",function(ev){if(!cur)return;dx=Math.max(0,ev.changedTouches[0].clientX-startX);var row=cur.querySelector(".dayrow");if(row)row.style.transform="translateX("+dx+"px)";},{passive:true});root.addEventListener("touchend",function(){if(!cur)return;var row=cur.querySelector(".dayrow");if(dx>88){var d=cur.getAttribute("data-d");setTimeout(function(){dropMeal(d);},80);}else if(row)row.style.transform="";cur=null;dx=0;});})();
document.addEventListener("click",function(ev){var tog=ev.target.closest("[data-act=tog], .ck");if(tog){var k=tog.getAttribute("data-k")||(tog.closest(".swipewrap")&&tog.closest(".swipewrap").getAttribute("data-k"));if(k){S.checked[k]=!S.checked[k];if(typeof save==="function")save();if(typeof drawList==="function")drawList();ev.preventDefault();ev.stopPropagation();}return;}var qty=ev.target.closest("[data-act=qty]");if(qty){if(typeof bumpExtra==="function")bumpExtra(+qty.getAttribute("data-i"),+qty.getAttribute("data-d"));ev.preventDefault();ev.stopPropagation();return;}var g=ev.target.closest("[data-act=skupick]");if(g){pickSku(g.getAttribute("data-generic")==="1",+g.getAttribute("data-i"));return;}if(ev.target.closest(".qtybox"))return;var merk=ev.target.closest("#lijstbody .listrow b");if(merk){var w=merk.closest(".swipewrap");var k=w&&w.getAttribute("data-k");if(k&&k.indexOf("e:")!==0)openSku(k);}});
if(!document.getElementById("qtycss2")){var st=document.createElement("style");st.id="qtycss2";st.textContent=".qtybox{display:flex;align-items:center;gap:6px;flex:none;margin-left:8px}.qtybtn{width:34px;height:34px;border:0;border-radius:10px;background:#EDE0D0;font:800 18px Outfit,sans-serif;color:#2A1810}.qtyn{min-width:16px;text-align:center;font-weight:800}.ck{width:28px;height:28px;border-radius:8px;border:2px solid #C45A38;background:#fff;flex:none}.ck.on{background:#C45A38;color:#fff}";document.head.appendChild(st);}
try{if(document.getElementById("bord")&&document.getElementById("bord").classList.contains("on"))wireBordSwipe();}catch(e){}
