S.sku=S.sku||{};
function ensureSkuPanel(){if(document.getElementById("skup"))return;var p=document.createElement("section");p.className="panel";p.id="skup";p.innerHTML="<div class=hd><button class='btn s w' id=skclose>Sluit</button><b>Kies product</b></div><div class=sc><p class=note id=sknote></p><div id=skbody></div></div>";document.querySelector(".phone").appendChild(p);document.getElementById("skclose").onclick=function(){p.classList.remove("on");};}
function tokensOf(item){var n=(item&&(item.n||item.k)||"").toLowerCase();return n.split(/[^a-z0-9]+/).filter(function(w){return w.length>3&&["voor","met","van","stuks","pack"].indexOf(w)<0;});}
function skuMatches(item){var toks=tokensOf(item);var rows=(window.FOLDER_FULL&&window.FOLDER_FULL.items)||[];var stores=typeof activeStores==="function"?activeStores().map(function(s){return s.id;}):["ah","jumbo","lidl","plus","dirk"];return rows.filter(function(r){if(stores.indexOf(r.s)<0)return false;var hay=(r.n+" "+(r.b||"")).toLowerCase();return toks.some(function(t){return hay.indexOf(t)>=0;});}).slice(0,24);}
function openSku(k){ensureSkuPanel();var items=typeof buildList==="function"?buildList():[];var item=items.filter(function(i){return i.k===k;})[0]||{k:k,n:k};S._skuK=k;document.getElementById("sknote").textContent="Wat wil je precies voor "+item.n+"? Alleen merken uit jullie winkels, deze week.";var hits=skuMatches(item);var html="<button class=listrow data-act=skupick data-generic=1><div style=flex:1><b>"+item.n+"</b><div class=meta>Geen specifiek merk · jij kiest in de winkel</div></div></button>";hits.forEach(function(r,i){var price=r.now?("€"+(r.now/100).toFixed(2).replace(".",",")):"";html+="<button class=listrow data-act=skupick data-i="+i+"><div style=flex:1><b>"+r.n+"</b><div class=meta>"+storeName(r.s)+(r.b?" · "+r.b:"")+" · "+(r.deal||"actie")+"</div></div><div class=price>"+price+"</div></button>";});if(!hits.length)html+="<p class=note>Geen exacte hit in de folder. Kies generiek, of tik Actie en zet het merk zelf op de lijst.</p>";document.getElementById("skbody").innerHTML=html;window._skuHits=hits;document.getElementById("skup").classList.add("on");}
function pickSku(generic,idx){var k=S._skuK;if(!k)return;if(generic){delete S.sku[k];}else{var r=window._skuHits[idx];if(r)S.sku[k]={n:r.n,b:r.b||"",s:r.s,now:r.now,deal:r.deal};}if(typeof save==="function")save();document.getElementById("skup").classList.remove("on");if(typeof drawList==="function")drawList();if(typeof toast==="function")toast(generic?"Merk open gelaten":(S.sku[k].n+" gekozen"));}
function paintSkuNames(){if(!S.sku)return;document.querySelectorAll("#lijstbody .swipewrap").forEach(function(w){var k=w.getAttribute("data-k");var pick=S.sku[k];if(!pick)return;var b=w.querySelector("b");var m=w.querySelector(".meta");if(b)b.textContent=pick.n;if(m)m.textContent=(storeName(pick.s)||pick.s)+(pick.b?" · "+pick.b:"")+(pick.deal?" · "+pick.deal:"");});}
function wireBordSwipe(){var root=document.getElementById("days");if(!root)return;root.querySelectorAll(".dayrow").forEach(function(row){var d=row.getAttribute("data-d");if(!S.plan[d]||!S.plan[d].id)return;if(row.parentNode.classList.contains("swipewrap"))return;var wrap=document.createElement("div");wrap.className="swipewrap right";wrap.setAttribute("data-d",d);wrap.innerHTML="<div class=swipebg>Weg van bord</div>";row.parentNode.insertBefore(wrap,row);wrap.appendChild(row);});}
function dropMeal(d){delete S.plan[d];delete S.eaten[d];if(typeof save==="function")save();if(typeof drawBord==="function")drawBord();if(typeof toast==="function")toast("Gerecht eraf. Lijst is opnieuw opgebouwd.");}
if(typeof drawBord==="function"&&!drawBord._pick){var _b=drawBord;drawBord=function(){_b();wireBordSwipe();};drawBord._pick=true;}
if(typeof drawList==="function"&&!drawList._pick){var _l=drawList;drawList=function(){_l();paintSkuNames();};drawList._pick=true;}
(function(){var root=document.getElementById("days");if(!root)return;var startX=0,cur=null,dx=0,locked=false;root.addEventListener("touchstart",function(ev){var wrap=ev.target.closest(".swipewrap.right");if(!wrap||ev.target.closest("button"))return;startX=ev.changedTouches[0].clientX;cur=wrap;dx=0;locked=false;var row=wrap.querySelector(".dayrow");if(row)row.style.transition="none";},{passive:true});root.addEventListener("touchmove",function(ev){if(!cur)return;var adx=ev.changedTouches[0].clientX-startX;if(Math.abs(adx)>12)locked=true;if(!locked)return;dx=Math.max(0,adx);var row=cur.querySelector(".dayrow");if(row)row.style.transform="translateX("+dx+"px)";},{passive:true});root.addEventListener("touchend",function(){if(!cur)return;var row=cur.querySelector(".dayrow");if(row)row.style.transition="transform .15s ease";if(dx>88){var d=cur.getAttribute("data-d");if(row)row.style.transform="translateX(100%)";setTimeout(function(){dropMeal(d);},140);}else if(row)row.style.transform="";cur=null;dx=0;});})();
document.addEventListener("click",function(ev){var name=ev.target.closest("#lijstbody .listrow > div");if(name&&!ev.target.closest(".ck")&&!ev.target.closest("[data-act=tog]")){var w=name.closest(".swipewrap");if(w&&w.getAttribute("data-k")){ev.preventDefault();openSku(w.getAttribute("data-k"));return;}}var g=ev.target.closest("[data-act=skupick]");if(g){pickSku(g.getAttribute("data-generic")==="1",+g.getAttribute("data-i"));}});
try{if(document.getElementById("bord")&&document.getElementById("bord").classList.contains("on"))wireBordSwipe();}catch(e){}
